import Login from "@/components/login/Login";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "UM | Login",
  description: "Generated by create next app",
};

const LoginPage = () => {
  return <Login />;
};

export default LoginPage;
